### ISSUE TITLE
Bug: Uncaught ReferenceError: init is not defined at onload (index.php:40:23)

### ISSUE THREAD

**Issue by JoeKae** [dmpop/pinpinpin#1]
While testing the project with docker i get the error `Uncaught ReferenceError: init is not defined at onload (index.php:40:23)` thrown in the console.

Docker:
`docker run -dit --name pinpinpin-app -p 80:80 -v path/to/pinpinpin:/var/www/html php:apache`

URL:
`http://localhost/index.php`

**Comment by dmpop** [comment]
My JavaScript skills are not up to scratch, to say the least. But I think I've fixed the issue in https://github.com/dmpop/pinpinpin/commit/4867d5e11df36def6bc1db90f0646ae52882a4d0

Thank you for reporting the issue, and I'd be grateful if you confirm that the fix works.

**Comment by JoeKae** [comment]
The `init()` error is gone. Now i got a blank screen.
What php version did you use for development?

**Comment by dmpop** [comment]
8.1, but I'm not sure whether the problem is on the PHP or JS side.

**Comment by JoeKae** [comment]
If you run the app using the docker command i provided, do you encounte the same problem?

**Comment by JoeKae** [comment]
Using the image  `php:8.1-apache` i get the same problem.
Unfortunately there are no errors in the console.

**Comment by dmpop** [comment]
Runs fine with PHP 8.1.2 built-in server. I might test Docker later, if time permits.

**Comment by dmpop** [comment]
Come to think of it, PinPinPin requires the PHP-GD and PHP-EXIF libraries. PHP-GD is usually enabled in the standard PHP configuration, but PHP-EXIF is not. Does the Docker image you're using have PHP-EXIF?

**Comment by JoeKae** [comment]
Good point.

I did create a Dockerfile to build an image with exif and gd support:

```
FROM php:8.1-apache

RUN apt-get update && apt-get install -y \
		libfreetype6-dev \
		libjpeg62-turbo-dev \
		libpng-dev \
	&& docker-php-ext-configure gd --with-freetype --with-jpeg \
	&& docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install exif \
    && docker-php-ext-enable exif

COPY ./ /var/www/html/
```
`docker build -t pinpinpin .`
`docker run --rm -it --name pinpinpin-app -p 80:80 pinpinpin`

Still a blank screen. I will set up a webserver to test it without docker.

**Comment by JoeKae** [comment]
Now i get a console error again though:
```
Uncaught SyntaxError: Unexpected token '<'
(index):301 Uncaught ReferenceError: init is not defined
    at onload ((index):301:23)
```

**Comment by JoeKae** [comment]
I am rusty with php but maybe it is not allowed in a js scriptblock

https://github.com/dmpop/pinpinpin/blob/4867d5e11df36def6bc1db90f0646ae52882a4d0/index.php#L126-L171

**Comment by JoeKae** [comment]
I got it working... kind of.

First i realized that some Arraykeys are missing in my images exif data. So i added the [coalesce operator](https://wiki.php.net/rfc/isset_ternary) to each line with an expected array key.

**Example**
```php
$lens = $exif["EXIF"]["UndefinedTag:0xA434"] ?? null;
```

After hat the console complained about a missing variable named background. So i commented out the line:

```php
// L.control.layers(background, overlays).addTo(map);
```

Does this help you? Whats up with the missing background?

**Comment by dmpop** [comment]
Thanks for investigating it! So I added two files you can use to build a container image that works: `Dockerfile` (for use with Docker) and `buildah.sh` (for use with Podman). I've only tried the latter, and everything works with the `podman run -it --rm -p 8000:8000 pinpinpin` command.

Thanks for the tip about the coalesce operator! I've amended the code.

**Comment by JoeKae** [comment]
Thank you :)
